export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'
export const LOAD_CATEGORY_POSTS_SUCCESS = 'LOAD_CATEGORY_POSTS_SUCCESS'
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const LOAD_POST_BY_ID_SUCCESS = 'LOAD_POST_BY_ID_SUCCESS'
export const SAVE_EDITED_POST_SUCCESS = 'SAVE_EDITED_POST_SUCCESS'
//comments
export const LOAD_ALL_COMMENTS_BY_POST_ID_SUCCESS = 'LOAD_ALL_COMMENTS_BY_POST_ID_SUCCESS'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS'
export const ADD_NEW_POST = 'ADD_NEW_POST';
export const DELETE_POST = 'DELETE_POST'
export const VOTE_SCORE = 'VOTE_SCORE';
export const COMMENT_VOTE_SCORE = 'COMMENT_VOTE_SCORE'